campaigns = {"name": "campaigns",
             "type": "record",
             "fields": [{"name": "active",
                         "type": ["null", "boolean"],
                         "default": "null"},
                        {"name": "created_at",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "description",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "name",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "program_id",
                         "type": ["null", "int"],
                         "default": "null"},
                        {"name": "program_name",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "type",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "updated_at",
                         "type": ["null", "string"],
                         "default": "null"},
                        {"name": "workspace_name",
                         "type": ["null", "string"],
                         "default": "null"}
                        ]
             }
