lead_lists = {"name": "lead_lists",
              "type": "record",
              "fields": [{"name": "created_at",
                          "type": ["null", "string"],
                          "default": "null"},
                         {"name": "description",
                          "type": ["null", "string"],
                          "default": "null"},
                         {"name": "id",
                          "type": ["null", "int"],
                          "default": "null"},
                         {"name": "name",
                          "type": ["null", "string"],
                          "default": "null"},
                         {"name": "program_name",
                          "type": ["null", "string"],
                          "default": "null"},
                         {"name": "updated_at",
                          "type": ["null", "string"],
                          "default": "null"},
                         {"name": "workspace_name",
                          "type": ["null", "string"],
                          "default": "null"}
                         ]}
