leads = {"name": "leads",
         "type": "record",
         "fields": [{'default': 'null',
                     'name': 'company',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'site',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'date_for_meetin',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'd3_s_acct_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'operational_recon_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_street',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_city',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_state',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_country',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_postal_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'website',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'main_phone',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'annual_revenue',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'number_of_employees',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'industry',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sic_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mkto_company_notes',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_account_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_company_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_company_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'id',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'mkto_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'person_type',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mkto_is_partner',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'is_lead',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'mkto_is_customer',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'is_anonymous',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'salutation',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'first_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'middle_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'email',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'phone',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mobile_phone',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'fax',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'title',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'contact_company',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'date_of_birth',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'city',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'state',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'country',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'postal_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_source_type',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_source_info',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'registration_source_type',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'registration_source_info',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_search_engine',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_search_phrase',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_referrer',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'email_invalid',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'email_invalid_cause',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'unsubscribed',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'unsubscribed_reason',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'do_not_call',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'mkto_do_not_call_cause',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'do_not_call_reason',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mkto_person_notes',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_type',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_contact_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'anonymous_ip',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_company',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_country',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_city',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_state_region',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_postal_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_metropolitan_area',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_phone_area_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'department',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_contact_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_contact_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'created_at',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'updated_at',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_person',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_role',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_source',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_score',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'urgency',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'priority',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'relative_score',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'relative_urgency',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'rating',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_lead_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sfdc_lead_owner_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'person_primary_lead_interest',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_partition_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_revenue_cycle_model_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_revenue_stage_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'gender',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_display_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'twitter_display_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_display_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_profile_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'twitter_profile_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_profile_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_photo_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'twitter_photo_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_photo_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_reach',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'twitter_reach',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_reach',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_referred_visits',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'twitter_referred_visits',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_referred_visits',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'total_referred_visits',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_referred_enrollments',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'twitter_referred_enrollments',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_referred_enrollments',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'total_referred_enrollments',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_referred_visit',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_referred_enrollment',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'syndication_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'acquisition_program_id',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'mkto_acquisition_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_executive',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_executive_email',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_advocate',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_advocate_email',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sales_representative',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sales_representative_email',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'stated_interest',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'level',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_phone',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_city',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_state',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_postal_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_country',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'opt_out_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'product_solution_demo',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'discovery_workshop',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'half_day_event',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'roadshow',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'comments',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_stated_source',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'keep_in_touch',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cpe_request',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'doc_path',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'luncheon_city',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'role',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'icon2013_package',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'wednesday_webex',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tt',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_revenue',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'facebook_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'twitter_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'linked_in_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'webinar_registration_source',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'currency_iso_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'email_bounced_reason',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'email_bounced_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'submit_for_conversion_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sub_industry_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'do_not_contact_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'do_not_mail_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'lvm_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'log_call_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'quick_actions_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'set_meeting_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'set_task_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'db_lead_age_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'lid_linked_in_company_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lid_linked_in_member_token_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'attended_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'business_unit_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cpe_certification_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cpe_credits_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'conversion_with_opportunity_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'conversion_without_opportunity_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'discovery_workshop_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'half_day_event_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'icon_2013_package_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'infogix_ae_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'infogix_sr_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'is_customer_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'marketing_comments_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'next_step_comments_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'next_step_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'origination_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'primary_interest_driver_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'problem_project_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'product_solution_demo_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'role_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'secondary_email_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'team_member_generated_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'type_of_submission_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mkto_si_hide_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mkto_si_msi_contact_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'record_type_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'currency_iso_code_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sub_industry_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ps_customer_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'renewal_owner_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'risk_rating_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_type_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_email_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sf_external_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assigned_leader_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'members_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'claims_opp_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'claims_disp_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tier_level_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lid_linked_in_company_id_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'known_partners_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'auditor_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_owner_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'currency_iso_code_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'referenceable_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'extension_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'inactivate_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'golden_contact_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'half_day_event_c_contact',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'mkto_si_sales_insight_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ach_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'ach_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'aml_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'aml_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'actuarial_reserves_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'actuarial_reserves_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'banking_operations_percent_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'banking_operations_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'bill_collection_percent_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'bill_collection_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'card_settlement_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'card_settlement_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'claims_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'claims_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cost_sharing_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'cost_sharing_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_assessment_completed_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'customer_assessment_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'dq_mods_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'dq_mods_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'dw_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'dw_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'feeds_mgmt_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'feeds_mgmt_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'finan_recon_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'finan_recon_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'gl_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'gl_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'icd_10_testing_percent_c',
                     'type': ['null', 'double']},
                    {'default': 'null',
                     'name': 'icd_10_testing_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'installed_non_specific_area_count_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'installed_non_specific_area_list_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mlr_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mlr_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'membership_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'membership_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'on_pipeline_non_specific_area_count_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'on_pipeline_non_specific_area_list_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'operating_rules_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'operating_rules_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'operational_recon_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'payment_processing_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'payment_processing_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'provider_pymts_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'provider_pymts_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'regulatory_reporting_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'regulatory_reporting_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sox_naic_mar_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sox_naic_mar_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 's_e_eligible_mbrship_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 's_e_eligible_mbrship_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'statement_processing_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'statement_processing_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'trade_settlement_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'trade_settlement_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'x3_rs_percent_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'x3_rs_status_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ca_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_advocate_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_executive_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sales_representative_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'product_adoption_manager_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mktomerge',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_customer_assessment_score_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_assessment_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'next_customer_assessment_due_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'date_became_customer_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'not_identified_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'knows_infogix_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'acr_coder_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'assure_coder_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'business_user_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'decision_maker_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'recommender_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'champion_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'technical_resource_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'economic_buyer_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'procurement_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'contractor_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'gv_s_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'gv_s_assessment_due_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assessment_due_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'end_month_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'calculate_customer_assessment_due_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assessment_period_end_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'partner_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cookies',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_name_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_intimacy_score_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_intimacy_icon_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_period_end_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_change_score_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_change_icon_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_total_score_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_total_score_icon_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_usage_score_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'if_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'next_ca_due_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'next_ca_due_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'most_recent_ca_total_icon_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'us_international_split_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'us_international_flag_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sr_priority_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'insightera_assets_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'insightera_campaigns_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'iera_asset_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'iera_campaign_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'db_created_date_without_time_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ddc_prospector_sourced_from_data_com_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_18digit_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'legacy_account_owner_del_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'legacy_renewal_owner_del_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ddc_prospector_sourced_from_data_com_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'legacy_person_id_del_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ddc_prospector_sourced_from_data_com_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'addl_call_details_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'region_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'coach_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'influencer_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'nick_name_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assistant_direct_number_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assistant_s_extension_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'assistant_email_address_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ag_account_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ag_data_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ag_contact_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ag_data_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ag_lead_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'controlsvs_analytics',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'controlsandanalytics',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'focus',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_ardi_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_ar_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_as_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_atz_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_av_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_les_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_bar_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_bas_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_bav_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_brdi_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_btz_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_sar_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_sas_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_sav_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_srdi_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_stz_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_ces_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_mar_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_mas_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_mav_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_mrdi_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_mtz_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_oar_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_oas_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_oav_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_ordi_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'cloudingo_agent_otz_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'schedule_a_call_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'iera_campaign',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'iera_asset',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'seconday_phone_number_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'vertical',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mktg_industry_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'birthday_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'external_company_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'demographic_score',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'comment_capture',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'comment_h_istory',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'behavior_score',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'external_sales_person_id',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'key_contact_info_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'contact_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lifecycle_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'marketing_qualified_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'reason_will_never_buy_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'wbx_is_this_home_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'wbx_receive_cpe_credit',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'wbx_comments1',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'wbx_is_this_your_home_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ind_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'not_valid_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'invalid_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'qbr_participant_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'x2017_dates_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'x2017_comments_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'ca_key_contact_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'tr_full_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tr_is_home_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tr_is_home_address2',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tr_receive_cpe_credit',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tr_selected_courses',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'db_creator_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'db_creator_auto_populate_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sub_category_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_success_rep_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sr_prospecting_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'priority_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sr_focus_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'i_sell_os_key_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'i_sell_os_key_id_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'c_or_p_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tt_itda_watch_tech_target_import_timestamp_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'time_zone_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'reason_why_na_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sales_campaign_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'lead_score_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'acquisition_program_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'acquisition_program_id_2017_c',
                     'type': ['null', 'long']},
                    {'default': 'null',
                     'name': 'acquisition_date_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_search_phrase_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_source_info_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_source_type_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_referrer_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'original_search_engine_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_company_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_metropolitan_area_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_phone_area_code_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_state_region_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_city_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_postal_code_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'inferred_country_2017_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'job_function',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'invoice_payments_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'ns_subsidiary_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'd3_s_data_c',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'd3_s_acct_id_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'd3_s_contact_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'd3_s_data_c_contact',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'latitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'longitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'geocode_accuracy',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'address_lead',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'photo_url',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_viewed_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_referenced_date',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_contact_id_lead',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'clean_status',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'company_duns_number',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_latitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_longitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_geocode_accuracy',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'billing_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'shipping_latitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'shipping_longitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'shipping_geocode_accuracy',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'shipping_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'photo_url_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_viewed_date_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'last_referenced_date_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'jigsaw_company_id_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'clean_status_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'account_source',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'duns_number',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'tradestyle',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'naics_code',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'naics_desc',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'year_started',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'sic_desc',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'other_latitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'other_longitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'other_geocode_accuracy',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'other_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mailing_latitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mailing_longitude',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mailing_geocode_accuracy',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'mailing_address',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'is_email_bounced',
                     'type': ['null', 'boolean']},
                    {'default': 'null',
                     'name': 'netsuite_conn_account_balance_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_account_overdue_balance_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_celigo_update_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_channel_tier_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_credit_hold_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_credit_limit_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_days_overdue_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_net_suite_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_net_suite_sync_err_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_push_to_net_suite_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_pushed_from_opportunity_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_sync_in_progress_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_unbilled_orders_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_celigo_update_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_net_suite_customer_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_net_suite_id_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_net_suite_sync_err_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_push_to_net_suite_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_pushed_from_opportunity_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'netsuite_conn_sync_in_progress_c_contact',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'email_code_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'customer_programs_manager_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'iwanttotalkwith',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'contact_us_comments',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'marketing_suspended_reason',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'path_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'legal_file_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_job_function',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_title',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_company',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_first_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_last_name',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'z_i_person_job_title',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_info_email_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_info_industry_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_info_phone_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_info_trigger_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_id_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_lastupdated_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_info_industry_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_id_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'zisf_zoom_lastupdated_c_account',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'webinar1',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'webinar2',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'webinar3',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'webinar4',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'data_governance_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'big_data_quality_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'platform_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'dg_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'bdq_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'plat_date_c',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'person_time_zone',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'date_for_eetin',
                     'type': ['null', 'string']},
                    {'default': 'null',
                     'name': 'invoice_c',
                     'type': ['null', 'string']}
                    ]
         }
