programs = {"name": "programs",
            "type": "record",
            "fields": [{"name": "channel",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "created_at",
                                "type": ["null", "string"],
                                "default": "null"},
                       {"name": "id",
                        "type": ["null", "int"],
                        "default": "null"},
                       {"name": "description",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "folder",
                        "type": {
                            "name": "folder",
                            "type": "record",
                            "fields": [{"name": "folder_name",
                                        "type": ["null", "string"],
                                        "default": "null"},
                                       {"name": "type",
                                        "type": ["null", "string"],
                                        "default": "null"},
                                       {"name": "value",
                                        "type": ["null", "int"],
                                        "default": "null"}]}},
                       {"name": "name",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "status",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "type",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "updated_at",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "url",
                        "type": ["null", "string"],
                        "default": "null"},
                       {"name": "workspace",
                        "type": ["null", "string"],
                        "default": "null"},
                       ]
            }
